config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :religions do
    resources :categories do
      resources :subcategories do
        resources :products
      end
    end
  end

  resources :accessories

  resources :colors

  root 'religions#index'

  get 'api/religions', to: 'api#religions', defaults: {format: :json}
  get 'api/colors', to: 'api#colors', defaults: {format: :json}
  get 'api/accessories', to: 'api#accessories', defaults: {format: :json}

  post 'submision/create'
  get 'submision/new'

  resources :tests
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :religion
  has_many :subcategories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/color.rb
class Color < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory

  mount_uploader :image, ImageUploader

  validates_presence_of :model
end

app/models/religion.rb
class Religion < ApplicationRecord
  has_many :categories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :authenticate_user!

  def religions
    @religions = Religion.all
  end

  def colors
    @colors = Color.all
  end

  def accessories
    @accessories = Accessory.all
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  def index
    @category = Category.find params[:category_id]
    @subcategories = @category.subcategories
  end

  def show
    redirect_to religion_category_subcategory_products_path religion_id: @subcategory.category.religion.id, category_id: @subcategory.category.id, subcategory_id: @subcategory.id
  end

  def new
    @category = Category.find params[:category_id]
    @subcategory = @category.subcategories.build
  end

  def edit
    @category = Category.find params[:category_id]
  end

  def create
    @category = Category.find params[:category_id]
    @subcategory = @category.subcategories.create(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to religion_category_subcategories_path(religion_id: @subcategory.category.religion.id, category_id: @subcategory.category.id), notice: 'Subcategory was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to religion_category_subcategories_path(religion_id: @subcategory.category.religion.id, category_id: @subcategory.category.id), notice: 'Subcategory was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to religion_category_subcategories_path(religion_id: @subcategory.category.religion.id, category_id: @subcategory.category.id), notice: 'Subcategory was successfully destroyed.' }
    end
  end

  private
  def set_subcategory
    @subcategory = Subcategory.find params[:id]
  end

  def subcategory_params
    params.require(:subcategory).permit(:title, :image)
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opened_menu( request_path, current_path)
    # 1
    if request_path == '/religions'
      classes = (current_path.match(/\/religions\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
    #2
    elsif request_path.match(/\/religions\/\d+\/\w+$/)
      unless current_path.match(/\/religions(\/\d+\/\w+)?$/)
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #3
    elsif request_path.match(/\/religions\/\d+\/\w+\/\d+\/\w+$/)
      sub_path_array = request_path.split('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path = sub_path_array.join('/')
      if current_path.match(/\/religions(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path}(\/\d+\/\w+)?$/)
      else
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #4
    elsif request_path.match(/\/religions\/\d+\/\w+\/\d+\/\w+\/\d+\/\w+$/)
      sub_path_array = request_path.split('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path = sub_path_array.join('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path_ = sub_path_array.join('/')

      if current_path.match(/\/religions(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path}(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path_}(\/\d+\/\w+)?$/)
      else
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #5
    else
      classes = ' close-menu '
    end

    classes
  end

  def active_menu(current)
    classes = current ? 'active-menu ' : ''
  end

  def count(path)
    path.split('/').length
  end

  def delete_icon
    content_tag :span, class: 'delete-icon' do
      tag :img, src: asset_path('error.png')
    end
  end

  def edit_icon
    content_tag :span, class: 'edit-icon' do
      tag :img, src: asset_path('pencil.png')
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/religion_helper.rb
module ReligionHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/subcategories/_form.haml
= form_for [subcategory.category.religion, subcategory.category, subcategory], :html => {:multipart => true}  do |f|
  - if subcategory.errors.any?
    #error_explanation.alert.alert-warning
      %ul
        - subcategory.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title'
  .form-group
    = f.file_field :image, class: 'image-uploader'

  .form-group
    = f.submit 'Save', class: 'btn btn-primary btn-block'

app/views/subcategories/_subcategory.haml
.col-md-4
  .element{style: "background-image: url(#{subcategory.image}"}
    .right-block
      .top-block
        = link_to [subcategory.category.religion, subcategory.category, subcategory], :method => :delete, :data => { :confirm => 'Are you sure you want to delete this?' } do
          = delete_icon
      .bottom-block
        = link_to edit_religion_category_subcategory_path(religion_id: subcategory.category.religion.id, category_id: subcategory.category.id, id: subcategory.id) do
          = edit_icon
  .text-center
    %h4
      = link_to religion_category_subcategory_products_path religion_id: subcategory.category.religion.id, category_id: subcategory.category.id, subcategory_id: subcategory.id  do
        %h4
          = subcategory.title

app/views/subcategories/edit.html.haml
.container
  .text-center
    %h2 Editing subcategory
  .row
    .col-md-4
    .col-md-4
      = render 'form',  subcategory: @subcategory
  .text-center
    = link_to 'Cancel', religion_category_subcategories_path(@category.religion.id, @category.id)

app/views/subcategories/index.html.haml
.container
  .row
    .col-xs-12.col-sm-5.col-md-2.col-lg-2
      = render 'shared/left_menu'
    .col-xs-12.col-sm-7.col-md-10.col-lg10
      .content
        .row
          -@subcategories.each do |subcategory|
            = render 'subcategory',  subcategory: subcategory

        %br
        .row
          .col-md-4
          .col-md-4
            = link_to 'Add new', new_religion_category_subcategory_path(religion_id: @category.religion.id, category_id: @category.id), {class: 'btn btn-primary btn-lg btn-block'}
        %br

app/views/subcategories/new.html.haml
.container
  .text-center
    %h2 New subcategory
  .row
    .col-md-4
    .col-md-4
      = render 'form',  subcategory: @subcategory
  .text-center
    = link_to 'Cancel', religion_category_subcategories_path(@category.religion.id, @category.id)

app/views/subcategories/show.haml
.container
  .row
    .col-xs-12.col-sm-5.col-md-2.col-lg-2.left-bar

    .col-xs-12.col-sm-7.col-md-10.col-lg10
      .content
        .row
          -@categories.each do |category|
            = render 'categories/category',  category: category

        %br
        .row
          .col-md-4
          .col-md-4
            = link_to 'Add new', new_religion_path, {class: 'btn btn-primary btn-lg btn-block'}
        %br