config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :religions do
    resources :categories do
      resources :subcategories do
        resources :products
      end
    end
  end

  resources :accessories

  resources :colors

  root 'religions#index'

  get 'api/religions', to: 'api#religions', defaults: {format: :json}
  get 'api/colors', to: 'api#colors', defaults: {format: :json}
  get 'api/accessories', to: 'api#accessories', defaults: {format: :json}

  post 'submision/create'
  get 'submision/new'

  resources :tests
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :religion
  has_many :subcategories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/color.rb
class Color < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory

  mount_uploader :image, ImageUploader

  validates_presence_of :model
end

app/models/religion.rb
class Religion < ApplicationRecord
  has_many :categories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :authenticate_user!

  def religions
    @religions = Religion.all
  end

  def colors
    @colors = Color.all
  end

  def accessories
    @accessories = Accessory.all
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/religion_helper.rb
module ReligionHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title Italmons
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          .navbar-brand= link_to 'ITALMONS', root_path

        %ul.nav.navbar-nav.navbar-right
          -if current_user
            %li= link_to 'Log out', destroy_user_session_path, method: :delete
          -else
            %li= link_to 'Log in', new_user_session_path
    .container
      - if flash[:notice]
        .alert.alert-success.alert-dismissable
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
          %center= notice
      - if flash[:alert]
        .alert.alert-danger.alert-dismissable
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
          %center= alert
    = yield

app/views/shared/_content.haml
.col-md-4
  .element{style: "background-image: url(#{content.image}"}
    .right-block
      .top-block
        -#= link_to 'd', content, :method => :delete, :data => { :confirm => 'Are you sure?' }
          -#= fa_icon 'times', class: 'ctrl-icon'
      .bottom-block
        = link_to edit_religion_path(id: content.id) do
          = edit_icon
  .text-center
    %h4
      = content.title

app/views/shared/_left_menu.haml
.left-bar
  .text-left
    = link_to religions_path do
      .nesting-0.menu-item{class: "#{active_menu(current_page?(religions_path))}"}
        Religion
    - Religion.all.each do |religion|
      = link_to religion_categories_path(religion) do
        .nesting-1.menu-item{class: "#{active_menu(current_page?(religion_categories_path(religion)))} #{opened_menu(request.path, religion_categories_path(religion))}"}
          = religion.title[0..12]
      - religion.categories.each do |category|
        = link_to religion_category_subcategories_path(religion, category) do
          .nesting-2.menu-item{class: "#{active_menu(current_page?(religion_category_subcategories_path(religion, category)))} #{opened_menu(request.path, religion_category_subcategories_path(religion, category))}"}
            = category.title[0..12]
        - category.subcategories.each do |subcategory|
          = link_to religion_category_subcategory_products_path(religion, category, subcategory) do
            .nesting-3.menu-item{class: "#{active_menu(current_page?(religion_category_subcategory_products_path(religion, category, subcategory)))} #{opened_menu(request.path, religion_category_subcategory_products_path(religion, category, subcategory))}"}
              = subcategory.title[0..12]

  .text-left
    = link_to colors_path do
      .nesting-0.menu-item{class: "#{active_menu(current_page?(colors_path))}"}
        Colour
  .text-left
    = link_to accessories_path do
      .nesting-0.menu-item{class: "#{active_menu(current_page?(accessories_path))}"}
        Accessories
  .text-left
    = link_to submision_new_path do
      .nesting-0.menu-item{class: "#{active_menu(current_page?(submision_create_path))}"}
        Submission