config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :religions do
    resources :categories do
      resources :subcategories do
        resources :products
      end
    end
  end

  resources :accessories

  resources :colors

  root 'religions#index'

  get 'api/religions', to: 'api#religions', defaults: {format: :json}
  get 'api/colors', to: 'api#colors', defaults: {format: :json}
  get 'api/accessories', to: 'api#accessories', defaults: {format: :json}

  post 'submision/create'
  get 'submision/new'

  resources :tests
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :religion
  has_many :subcategories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/color.rb
class Color < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory

  mount_uploader :image, ImageUploader

  validates_presence_of :model
end

app/models/religion.rb
class Religion < ApplicationRecord
  has_many :categories, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :authenticate_user!

  def religions
    @religions = Religion.all
  end

  def colors
    @colors = Color.all
  end

  def accessories
    @accessories = Accessory.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @religion = Religion.find params[:religion_id]
    @categories = @religion.categories
  end

  def show
    redirect_to religion_category_subcategories_path religion_id: @category.religion.id, category_id: @category.id
  end

  def new
    @religion = Religion.find params[:religion_id]
    @category = @religion.categories.build
  end

  def edit
    @religion = Religion.find params[:religion_id]
  end

  def create
    @religion = Religion.find params[:religion_id]
    @category = @religion.categories.create(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to religion_categories_path(religion_id: @religion.id), notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to religion_categories_path(religion_id: @category.religion.id), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to religion_categories_path(religion_id: @category.religion.id), notice: 'Category was successfully destroyed.' }
    end
  end

  private
  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit(:title, :image)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def index
    @religions = Religion.all
    @items = [
        {name: 'main1', subs: [
            {name: 'subs1', subs: %w[subsub1 subsub2]},
            {name: 'subs2', subs: %w[subsub3 subsub4]}
        ]},
        {name: 'main2', subs: [
            {name: 'subs3', subs: %w[subsub11 subsub12]},
            {name: 'subs4', subs: %w[subsub13 subsub14]}
        ]}
    ]
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:test, :test1)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opened_menu( request_path, current_path)
    # 1
    if request_path == '/religions'
      classes = (current_path.match(/\/religions\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
    #2
    elsif request_path.match(/\/religions\/\d+\/\w+$/)
      unless current_path.match(/\/religions(\/\d+\/\w+)?$/)
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #3
    elsif request_path.match(/\/religions\/\d+\/\w+\/\d+\/\w+$/)
      sub_path_array = request_path.split('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path = sub_path_array.join('/')
      if current_path.match(/\/religions(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path}(\/\d+\/\w+)?$/)
      else
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #4
    elsif request_path.match(/\/religions\/\d+\/\w+\/\d+\/\w+\/\d+\/\w+$/)
      sub_path_array = request_path.split('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path = sub_path_array.join('/')
      sub_path_array.pop
      sub_path_array.pop
      sub_path_ = sub_path_array.join('/')

      if current_path.match(/\/religions(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path}(\/\d+\/\w+)?$/)
      elsif current_path.match(/#{sub_path_}(\/\d+\/\w+)?$/)
      else
        classes = (current_path.match(/#{request_path}\/\d+\/\w+$/)) ? ' opened-menu ' : ' close-menu '
      end
    #5
    else
      classes = ' close-menu '
    end

    classes
  end

  def active_menu(current)
    classes = current ? 'active-menu ' : ''
  end

  def count(path)
    path.split('/').length
  end

  def delete_icon
    content_tag :span, class: 'delete-icon' do
      tag :img, src: asset_path('error.png')
    end
  end

  def edit_icon
    content_tag :span, class: 'edit-icon' do
      tag :img, src: asset_path('pencil.png')
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/religion_helper.rb
module ReligionHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/categories/_category.haml
.col-md-4
  .element{style: "background-image: url(#{category.image}"}
    .right-block
      .top-block
        = link_to [category.religion, category], :method => :delete, :data => { :confirm => 'Are you sure you want to delete this?' } do
          = delete_icon
      .bottom-block
        = link_to edit_religion_category_path(category.religion, category) do
          = edit_icon
  .text-center
    %h4
      = link_to religion_category_subcategories_path religion_id: category.religion.id, category_id: category.id do
        %h4
          = category.title

app/views/categories/_form.haml
= form_for [category.religion, category], :html => {:multipart => true}  do |f|
  - if category.errors.any?
    #error_explanation.alert.alert-warning
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title'
  .form-group
    = f.file_field :image, class: 'image-uploader'

  .form-group
    = f.submit 'Save', class: 'btn btn-primary btn-block'

app/views/categories/edit.html.haml
.container
  .text-center
    %h2 Editing category
  .row
    .col-md-4
    .col-md-4
      = render 'form',  category: @category
  .text-center
    = link_to 'Cancel', religion_categories_url(@category.religion.id)

app/views/categories/index.html.haml
.container
  .row
    .col-xs-12.col-sm-5.col-md-2.col-lg-2
      = render 'shared/left_menu'
    .col-xs-12.col-sm-7.col-md-10.col-lg10
      .content
        .row
          -@categories.each do |category|
            = render 'category',  category: category

        %br
        .row
          .col-md-4
          .col-md-4
            = link_to 'Add new', new_religion_category_path(religion_id: @religion.id), {class: 'btn btn-primary btn-lg btn-block'}
        %br

app/views/categories/new.html.haml
.container
  .text-center
    %h2 New category
  .row
    .col-md-4
    .col-md-4
      = render 'form',  category: @category
  .text-center
    = link_to 'Cancel', religion_categories_url(@religion.id)

app/views/categories/show.haml
.container
  .row
    .col-xs-12.col-sm-5.col-md-2.col-lg-2.left-bar

    .col-xs-12.col-sm-7.col-md-10.col-lg10
      .content
        .row
          -@categories.each do |category|
            = render 'categories/category',  category: category

        %br
        .row
          .col-md-4
          .col-md-4
            = link_to 'Add new', new_religion_path, {class: 'btn btn-primary btn-lg btn-block'}
        %br